# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Api-Alamofire' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Api-Alamofire
	pod 'Alamofire', '~> 4.7.0'
  target 'Api-AlamofireTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Api-AlamofireUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
